targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/**/*_model.dart
          - features/**/*_model.dart
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          - lib/**/*_model.dart
          - features/**/*_model.dart