import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';
import 'package:mediconsult/features/prescriptions/domain/usecases/create_prescription.dart';
import 'package:mediconsult/features/prescriptions/domain/usecases/update_prescription.dart';
import 'package:mediconsult/features/prescriptions/domain/entities/prescription.dart';
import 'package:mediconsult/features/prescriptions/domain/entities/medication.dart';
import 'package:mediconsult/features/prescriptions/domain/enums/prescription_status.dart';
import 'create_prescription_event.dart';
import 'create_prescription_state.dart';

/// BLoC for managing create prescription state
@Injectable()
class CreatePrescriptionBloc
    extends Bloc<CreatePrescriptionEvent, CreatePrescriptionState> {
  final CreatePrescription _createPrescription;
  final UpdatePrescription _updatePrescription;

  CreatePrescriptionBloc({
    required CreatePrescription createPrescription,
    required UpdatePrescription updatePrescription,
  })  : _createPrescription = createPrescription,
        _updatePrescription = updatePrescription,
        super(CreatePrescriptionInitial()) {
    on<InitializePrescription>(_onInitializePrescription);
    on<AddMedication>(_onAddMedication);
    on<RemoveMedication>(_onRemoveMedication);
    on<UpdatePrescriptionDetails>(_onUpdatePrescriptionDetails);
    on<SavePrescription>(_onSavePrescription);
  }

  /// Handle initializing a new prescription
  Future<void> _onInitializePrescription(
    InitializePrescription event,
    Emitter<CreatePrescriptionState> emit,
  ) async {
    final prescription = Prescription(
      id: '', // Will be generated by repository
      consultationId: event.consultationId,
      patientId: event.patientId,
      patientName: event.patientName,
      patientAge: event.patientAge,
      patientGender: event.patientGender,
      doctorId: event.doctorId,
      doctorName: event.doctorName,
      doctorSpecialization: event.doctorSpecialization,
      doctorLicenseNumber: event.doctorLicenseNumber,
      medications: const [],
      prescribedDate: DateTime.now(),
      status: PrescriptionStatus.draft,
      createdAt: DateTime.now(),
    );

    emit(CreatePrescriptionEditing(
      prescription: prescription,
      isValid: false,
    ));
  }

  /// Handle adding a medication
  Future<void> _onAddMedication(
    AddMedication event,
    Emitter<CreatePrescriptionState> emit,
  ) async {
    if (state is CreatePrescriptionEditing) {
      final currentState = state as CreatePrescriptionEditing;
      final updatedMedications =
          List<Medication>.from(currentState.prescription.medications)
            ..add(event.medication);

      final updatedPrescription = currentState.prescription.copyWith(
        medications: updatedMedications,
      );

      emit(currentState.copyWith(
        prescription: updatedPrescription,
        isValid: updatedMedications.isNotEmpty,
      ));
    }
  }

  /// Handle removing a medication
  Future<void> _onRemoveMedication(
    RemoveMedication event,
    Emitter<CreatePrescriptionState> emit,
  ) async {
    if (state is CreatePrescriptionEditing) {
      final currentState = state as CreatePrescriptionEditing;
      final updatedMedications =
          List<Medication>.from(currentState.prescription.medications)
            ..removeWhere((med) => med.id == event.medicationId);

      final updatedPrescription = currentState.prescription.copyWith(
        medications: updatedMedications,
      );

      emit(currentState.copyWith(
        prescription: updatedPrescription,
        isValid: updatedMedications.isNotEmpty,
      ));
    }
  }

  /// Handle updating prescription details
  Future<void> _onUpdatePrescriptionDetails(
    UpdatePrescriptionDetails event,
    Emitter<CreatePrescriptionState> emit,
  ) async {
    if (state is CreatePrescriptionEditing) {
      final currentState = state as CreatePrescriptionEditing;
      final updatedPrescription = currentState.prescription.copyWith(
        diagnosis: event.diagnosis,
        notes: event.notes,
        pharmacyNotes: event.pharmacyNotes,
        validUntil: event.validUntil,
        refillsAllowed: event.refillsAllowed,
      );

      emit(currentState.copyWith(
        prescription: updatedPrescription,
      ));
    }
  }

  /// Handle saving the prescription
  Future<void> _onSavePrescription(
    SavePrescription event,
    Emitter<CreatePrescriptionState> emit,
  ) async {
    emit(CreatePrescriptionLoading());

    // Determine if this is a create or update operation
    final isUpdate = event.prescription.id.isNotEmpty &&
        event.prescription.id != '';

    // Update status to active if it's a draft
    final prescriptionToSave =
        event.prescription.status == PrescriptionStatus.draft
            ? event.prescription.copyWith(
                status: PrescriptionStatus.active,
                id: isUpdate
                    ? event.prescription.id
                    : DateTime.now().millisecondsSinceEpoch.toString(),
              )
            : event.prescription;

    // Use appropriate use case based on operation type
    final result = isUpdate
        ? await _updatePrescription(
            UpdatePrescriptionParams(prescription: prescriptionToSave))
        : await _createPrescription(
            CreatePrescriptionParams(prescription: prescriptionToSave));

    result.fold(
      (failure) => emit(CreatePrescriptionError(failure.toString())),
      (prescription) => emit(CreatePrescriptionSuccess(prescription)),
    );
  }
}
